apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nio87m34e-go 
  janus-idp.io/tekton: nio87m34e-go
  backstage.io/kubernetes-id: nio87m34e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nio87m34e-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  